### ISSUE TITLE
Would love to know how to make something like this for babel-node

### ISSUE THREAD

**Issue by fasiha** [borisdiakur/n_#12]
And other ES6 transpiler REPLs. I know it's not very open-source-spririted of me (not having a solution to share), but I love `n_` so much I'm not sure I can use babel-node without babel-n_.

**Comment by borisdiakur** [comment]
Here is a nice introduction on how to build your own REPL, which should get you started: [Build Your Own App Specific REPL For Your NodeJS App](http://derickbailey.com/2014/07/02/build-your-own-app-specific-repl-for-your-nodejs-app/). And of course it also in the node docs: https://nodejs.org/api/repl.html Then I'd search for `require("repl")` in babel's source code (you'll find it [here](https://github.com/babel/babel/blob/master/packages/babel-cli/bin/_babel-node#L9)), which should get you even more started. Hope that it helps you in finding your solution.

**Comment by esjay** [comment]
@fasiha Just as a followup to your question, I had the same need, so I made [babel-n_](https://github.com/esjay/babel-n_).
