### ISSUE TITLE
Upgrade to lodash 4.0

### ISSUE THREAD

**Issue by abhisekp** [borisdiakur/n_#14]
With the release of [**`[Lodash 4.0]`**](https://github.com/lodash/lodash/releases/tag/4.0.0), it will be nice to upgrade `n_` to the latest release.

Also it will be nice to tag the `n_` repo same as the lodash version.

**Comment by borisdiakur** [comment]
@abhisekp Thanks for the heads up!
I've released a new major version and tagged it with the annotated tag __v1.0.0__ using __lodash@4.x__ as the description. See https://github.com/borisdiakur/n_/releases

References:
    https://github.com/borisdiakur/n_/commit/08ea83a143567c9c5e01b9003951f0d9d61aa672

**Comment by abhisekp** [comment]
thanks :+1: :smile:
