### ISSUE TITLE
The special variable $ no longer works in Node 6

### ISSUE THREAD

**Issue by not-an-aardvark** [borisdiakur/n_#17]
I'm using n_ 1.3.0 and Node 6.0.0.

Instead of being assigned to the most recent output (as it was in Node 5), the variable `$` is simply assigned to lodash in Node 6.

```js
n_ > 123
123
n_ > $ // should be 123
{ [Function: lodash]
  templateSettings: 
   { escape: /<%-([\s\S]+?)%>/g,
     evaluate: /<%([\s\S]+?)%>/g,
     interpolate: /<%=([\s\S]+?)%>/g,
     variable: '',
     imports: { _: [Circular] } },
  after: [Function: after],
  ...
}
```

The issue might be related to [this change](/nodejs/node/pull/5535).

**Comment by borisdiakur** [comment]
> If assigned, the default behavior of assigning _ to the last evaluated expression is disabled, and _ now references whatever value was explicitly set. A warning is issued on the repl - 'expression assignment to _ now disabled'.

So this seems to be the new intended behaviour in the node repl which is sad in my opinion. Currently I can not think of a fix which would retain the old behaviour. The simplest think to do would be to just disable that feature. But I don’t know if this is smart. I’ll keep this issue open for a discussion on how to deal with this.
