### ISSUE TITLE
Allow custom lodash version

### ISSUE THREAD

**Issue by jonathankau** [borisdiakur/n_#18]
Would be useful to be able to specify which lodash version `n_` relies on, since I'm working on a project that still relies on version 3.10.1.

Not sure if that's possible (https://github.com/npm/npm/issues/5499 may be relevant), but at the very least I'll probably just fork and patch for now 😄

**Comment by borisdiakur** [comment]
I’m also working on projects which still rely on lodash@3.x, so to me this is a valid feature request. I think we could use [npm-install-version](https://github.com/scott113341/npm-install-version) in a post install script to install additional major versions, then put another file into the bin directory, let’s call it n_3, in that file set an environment variable, read it in lib/n_.js and load the required version. Something like that.

**Comment by jfmengels** [comment]
Awesome, thanks!

**Comment by jfmengels** [comment]
Hmm. I tried it out and it can't find `n_3`. Am I the only one? I think the binary needs to be explicitly added [here](https://github.com/borisdiakur/n_/commit/b6654e8acfd6cb0647fd0524edf9a074b78a67a8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7)

**Comment by borisdiakur** [comment]
@jfmengels You are right!

**Comment by borisdiakur** [comment]
Done. Sorry all. Please use n_@^1.4.1

**Comment by jfmengels** [comment]
Hmm, I'm getting an error when I run `n_3` (error pops out immediately and crashes the program)

```bash
$ n_3
n_ > module.js:457
    throw err;
    ^

Error: Cannot find module 'lodash@^3.10.1'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jeroen/.nvm/versions/node/v6.5.0/lib/node_modules/n_/lib/n_.js:26:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by borisdiakur** [comment]
Problem is that [npm-install-version](https://github.com/scott113341/npm-install-version) doesn’t install lodash@^3.10.1. I’ll open up an issue there.

**Comment by borisdiakur** [comment]
I have released version 1.4.2 which works for me and travis-ci. Please try it out and tell me if it works for you. I’ll then close this issue. Sorry for the frequent patch releases.

**Comment by jfmengels** [comment]
It works :) Thanks for the quick implementation and fixes!

> Sorry for the frequent patch releases.

Absolutely no problem ;)

**Comment by jfmengels** [comment]
Sidenote: `n_3 --fp` gives Lodash v4. But that's not so odd as fp did not exist in v3.

**Comment by borisdiakur** [comment]
@jfmengels Feels weird. It should throw. I’ll bump once more.
