### ISSUE TITLE
n_ breaks npm ls -g

### ISSUE THREAD

**Issue by chocolateboy** [borisdiakur/n_#19]
n_: 1.4.3
npm: 4.0.5
OS: Linux (Arch)

Running:

    npm ls -g --depth 0

results in the following error:

> npm ERR! extraneous: lodash3 \~/.nvm/versions/node/v7.2.1/lib/node_modules/n_/node_modules/lodash3
npm ERR! error in \~/.nvm/versions/node/v7.2.1/lib/node_modules/n_/node_modules/lodash3: ENOENT: no such file or directory, open '~/.nvm/versions/node/v7.2.1/lib/node_modules/n_/node_modules/lodash3/package.json'

This error doesn't occur with n_\@1.3.1. Something to do with [this](https://github.com/borisdiakur/n_/issues/18)?

**Comment by borisdiakur** [comment]
Fixed in n_@1.4.4
