### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Trial-In-Error** [borisdiakur/n_#20]
Using n_@1.4.4 and node@7.4.0, (almost) any input results in this warning being printed:

`DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by borisdiakur** [comment]
The [repl.history](https://github.com/tmpvar/repl.history) module, which n_ uses to persist its repl history, writes to the file without providing a callback: https://github.com/tmpvar/repl.history/blob/master/index.js#L15

I will report it there, probably send a PR. This should be resolved quickly.

**Comment by borisdiakur** [comment]
The [PR](https://github.com/tmpvar/repl.history/pull/11) has been accepted and a new version of [repl.history](https://github.com/tmpvar/repl.history) has been published.
https://github.com/tmpvar/repl.history/pull/11#issuecomment-275763845
You can now reinstall n_ and the warning will be gone.
