### ISSUE TITLE
Running on NodeJs v20 locally, interactive session not working

### ISSUE THREAD

**Issue by jaredschrag** [borisdiakur/n_#47]
Local NodeJS version is v20.10.0:
`$ node -v`
`v20.10.0`

After installing:
`npm install -g n_`

Running `n_` does not work, seems to show an error within the interactive session:
`$ n_`
`n_ > Value of "this" must be of type nullish or must be the global object`

**Comment by jaredschrag** [comment]
After installing `n_` globally, it shows version 4.0.0 is installed:
`$ npm ls -g n_`
```
C:\Program Files\nodejs -> .\
└── n_@4.0.0
```

**Comment by borisdiakur** [comment]
Hey @jaredschrag , thanks for reporting this issue. I've fixed it and released a patch version of n_ which should work in Node 20 and 21. Please update to n_ v4.0.1 🚀
