### ISSUE TITLE
Multi-line commands break lodash binding

### ISSUE THREAD

**Issue by venning** [borisdiakur/n_#9]
I have a weird error: if I run a multi-line command in the REPL (one that causes the `...` prefix) and I run that command *before* I run any command containing `_`, the binding to lodash gets lost somehow.

You should be able to repeat this behavior by starting `n_` and immediately running the two commands found in [this example](https://lodash.com/docs#sortByAll).  It should work with any arbitrary multi-line command, as long as that command occurs before any usage of `_`.

If you run a command containing `_` first, there is no problem.  Is this expected behavior?
![screen shot 2015-02-23 at 12 31 50 pm](https://cloud.githubusercontent.com/assets/3902717/6333071/fd3ca1e4-bb57-11e4-836a-3b1d20938306.png)

**Comment by borisdiakur** [comment]
Closed with merge https://github.com/borisdiakur/n_/pull/10
